package com.zuo.smartbackground.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbggenerated
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.schedule_id
     *
     * @mbggenerated
     */
    private Integer scheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.patient_id
     *
     * @mbggenerated
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Hongkong")
    private Date bookTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_avaliablity
     *
     * @mbggenerated
     */
    private Boolean isAvaliablity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_cancle
     *
     * @mbggenerated
     */
    private Boolean isCancle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbggenerated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.schedule_id
     *
     * @return the value of book.schedule_id
     *
     * @mbggenerated
     */
    public Integer getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.schedule_id
     *
     * @param scheduleId the value for book.schedule_id
     *
     * @mbggenerated
     */
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.patient_id
     *
     * @return the value of book.patient_id
     *
     * @mbggenerated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.patient_id
     *
     * @param patientId the value for book.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_time
     *
     * @return the value of book.book_time
     *
     * @mbggenerated
     */
    public Date getBookTime() {
        return bookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_time
     *
     * @param bookTime the value for book.book_time
     *
     * @mbggenerated
     */
    public void setBookTime(Date bookTime) {
        this.bookTime = bookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.is_avaliablity
     *
     * @return the value of book.is_avaliablity
     *
     * @mbggenerated
     */
    public Boolean getIsAvaliablity() {
        return isAvaliablity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.is_avaliablity
     *
     * @param isAvaliablity the value for book.is_avaliablity
     *
     * @mbggenerated
     */
    public void setIsAvaliablity(Boolean isAvaliablity) {
        this.isAvaliablity = isAvaliablity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.is_cancle
     *
     * @return the value of book.is_cancle
     *
     * @mbggenerated
     */
    public Boolean getIsCancle() {
        return isCancle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.is_cancle
     *
     * @param isCancle the value for book.is_cancle
     *
     * @mbggenerated
     */
    public void setIsCancle(Boolean isCancle) {
        this.isCancle = isCancle;
    }
}