package com.zuo.smartbackground.model;

public class PatientRecordForDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.patient_record_id
     *
     * @mbggenerated
     */
    private Long patientRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.patient_id
     *
     * @mbggenerated
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.doctor_id
     *
     * @mbggenerated
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.admission_time
     *
     * @mbggenerated
     */
    private long admissionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.chief
     *
     * @mbggenerated
     */
    private String chief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.now_history
     *
     * @mbggenerated
     */
    private String nowHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.past_history
     *
     * @mbggenerated
     */
    private String pastHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.personal_history
     *
     * @mbggenerated
     */
    private String personalHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.family_history
     *
     * @mbggenerated
     */
    private String familyHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.physical_examination
     *
     * @mbggenerated
     */
    private String physicalExamination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.therapeutic_examination
     *
     * @mbggenerated
     */
    private String therapeuticExamination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_record.diagnosis
     *
     * @mbggenerated
     */
    private String diagnosis;

    public Long getPatientRecordId() {
        return patientRecordId;
    }

    public void setPatientRecordId(Long patientRecordId) {
        this.patientRecordId = patientRecordId;
    }

    public Integer getPatientId() {
        return patientId;
    }

    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    public Integer getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    public long getAdmissionTime() {
        return admissionTime;
    }

    public void setAdmissionTime(long admissionTime) {
        this.admissionTime = admissionTime;
    }

    public String getChief() {
        return chief;
    }

    public void setChief(String chief) {
        this.chief = chief;
    }

    public String getNowHistory() {
        return nowHistory;
    }

    public void setNowHistory(String nowHistory) {
        this.nowHistory = nowHistory;
    }

    public String getPastHistory() {
        return pastHistory;
    }

    public void setPastHistory(String pastHistory) {
        this.pastHistory = pastHistory;
    }

    public String getPersonalHistory() {
        return personalHistory;
    }

    public void setPersonalHistory(String personalHistory) {
        this.personalHistory = personalHistory;
    }

    public String getFamilyHistory() {
        return familyHistory;
    }

    public void setFamilyHistory(String familyHistory) {
        this.familyHistory = familyHistory;
    }

    public String getPhysicalExamination() {
        return physicalExamination;
    }

    public void setPhysicalExamination(String physicalExamination) {
        this.physicalExamination = physicalExamination;
    }

    public String getTherapeuticExamination() {
        return therapeuticExamination;
    }

    public void setTherapeuticExamination(String therapeuticExamination) {
        this.therapeuticExamination = therapeuticExamination;
    }

    public String getDiagnosis() {
        return diagnosis;
    }

    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }
}
