package com.zuo.smartbackground.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public PatientRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatientRecordIdIsNull() {
            addCriterion("patient_record_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdIsNotNull() {
            addCriterion("patient_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdEqualTo(Long value) {
            addCriterion("patient_record_id =", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdNotEqualTo(Long value) {
            addCriterion("patient_record_id <>", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdGreaterThan(Long value) {
            addCriterion("patient_record_id >", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdGreaterThanOrEqualTo(Long value) {
            addCriterion("patient_record_id >=", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdLessThan(Long value) {
            addCriterion("patient_record_id <", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdLessThanOrEqualTo(Long value) {
            addCriterion("patient_record_id <=", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdIn(List<Long> values) {
            addCriterion("patient_record_id in", values, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdNotIn(List<Long> values) {
            addCriterion("patient_record_id not in", values, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdBetween(Long value1, Long value2) {
            addCriterion("patient_record_id between", value1, value2, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdNotBetween(Long value1, Long value2) {
            addCriterion("patient_record_id not between", value1, value2, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(Integer value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(Integer value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(Integer value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(Integer value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(Integer value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<Integer> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<Integer> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(Integer value1, Integer value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Integer value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Integer value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Integer value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Integer value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Integer> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Integer> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeIsNull() {
            addCriterion("admission_time is null");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeIsNotNull() {
            addCriterion("admission_time is not null");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeEqualTo(Date value) {
            addCriterion("admission_time =", value, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeNotEqualTo(Date value) {
            addCriterion("admission_time <>", value, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeGreaterThan(Date value) {
            addCriterion("admission_time >", value, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("admission_time >=", value, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeLessThan(Date value) {
            addCriterion("admission_time <", value, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeLessThanOrEqualTo(Date value) {
            addCriterion("admission_time <=", value, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeIn(List<Date> values) {
            addCriterion("admission_time in", values, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeNotIn(List<Date> values) {
            addCriterion("admission_time not in", values, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeBetween(Date value1, Date value2) {
            addCriterion("admission_time between", value1, value2, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andAdmissionTimeNotBetween(Date value1, Date value2) {
            addCriterion("admission_time not between", value1, value2, "admissionTime");
            return (Criteria) this;
        }

        public Criteria andChiefIsNull() {
            addCriterion("chief is null");
            return (Criteria) this;
        }

        public Criteria andChiefIsNotNull() {
            addCriterion("chief is not null");
            return (Criteria) this;
        }

        public Criteria andChiefEqualTo(String value) {
            addCriterion("chief =", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotEqualTo(String value) {
            addCriterion("chief <>", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefGreaterThan(String value) {
            addCriterion("chief >", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefGreaterThanOrEqualTo(String value) {
            addCriterion("chief >=", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefLessThan(String value) {
            addCriterion("chief <", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefLessThanOrEqualTo(String value) {
            addCriterion("chief <=", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefLike(String value) {
            addCriterion("chief like", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotLike(String value) {
            addCriterion("chief not like", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefIn(List<String> values) {
            addCriterion("chief in", values, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotIn(List<String> values) {
            addCriterion("chief not in", values, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefBetween(String value1, String value2) {
            addCriterion("chief between", value1, value2, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotBetween(String value1, String value2) {
            addCriterion("chief not between", value1, value2, "chief");
            return (Criteria) this;
        }

        public Criteria andNowHistoryIsNull() {
            addCriterion("now_history is null");
            return (Criteria) this;
        }

        public Criteria andNowHistoryIsNotNull() {
            addCriterion("now_history is not null");
            return (Criteria) this;
        }

        public Criteria andNowHistoryEqualTo(String value) {
            addCriterion("now_history =", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryNotEqualTo(String value) {
            addCriterion("now_history <>", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryGreaterThan(String value) {
            addCriterion("now_history >", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("now_history >=", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryLessThan(String value) {
            addCriterion("now_history <", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryLessThanOrEqualTo(String value) {
            addCriterion("now_history <=", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryLike(String value) {
            addCriterion("now_history like", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryNotLike(String value) {
            addCriterion("now_history not like", value, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryIn(List<String> values) {
            addCriterion("now_history in", values, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryNotIn(List<String> values) {
            addCriterion("now_history not in", values, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryBetween(String value1, String value2) {
            addCriterion("now_history between", value1, value2, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andNowHistoryNotBetween(String value1, String value2) {
            addCriterion("now_history not between", value1, value2, "nowHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryIsNull() {
            addCriterion("past_history is null");
            return (Criteria) this;
        }

        public Criteria andPastHistoryIsNotNull() {
            addCriterion("past_history is not null");
            return (Criteria) this;
        }

        public Criteria andPastHistoryEqualTo(String value) {
            addCriterion("past_history =", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryNotEqualTo(String value) {
            addCriterion("past_history <>", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryGreaterThan(String value) {
            addCriterion("past_history >", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("past_history >=", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryLessThan(String value) {
            addCriterion("past_history <", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryLessThanOrEqualTo(String value) {
            addCriterion("past_history <=", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryLike(String value) {
            addCriterion("past_history like", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryNotLike(String value) {
            addCriterion("past_history not like", value, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryIn(List<String> values) {
            addCriterion("past_history in", values, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryNotIn(List<String> values) {
            addCriterion("past_history not in", values, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBetween(String value1, String value2) {
            addCriterion("past_history between", value1, value2, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPastHistoryNotBetween(String value1, String value2) {
            addCriterion("past_history not between", value1, value2, "pastHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryIsNull() {
            addCriterion("personal_history is null");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryIsNotNull() {
            addCriterion("personal_history is not null");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryEqualTo(String value) {
            addCriterion("personal_history =", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryNotEqualTo(String value) {
            addCriterion("personal_history <>", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryGreaterThan(String value) {
            addCriterion("personal_history >", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("personal_history >=", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryLessThan(String value) {
            addCriterion("personal_history <", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryLessThanOrEqualTo(String value) {
            addCriterion("personal_history <=", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryLike(String value) {
            addCriterion("personal_history like", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryNotLike(String value) {
            addCriterion("personal_history not like", value, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryIn(List<String> values) {
            addCriterion("personal_history in", values, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryNotIn(List<String> values) {
            addCriterion("personal_history not in", values, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryBetween(String value1, String value2) {
            addCriterion("personal_history between", value1, value2, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andPersonalHistoryNotBetween(String value1, String value2) {
            addCriterion("personal_history not between", value1, value2, "personalHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryIsNull() {
            addCriterion("family_history is null");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryIsNotNull() {
            addCriterion("family_history is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryEqualTo(String value) {
            addCriterion("family_history =", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryNotEqualTo(String value) {
            addCriterion("family_history <>", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryGreaterThan(String value) {
            addCriterion("family_history >", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("family_history >=", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryLessThan(String value) {
            addCriterion("family_history <", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryLessThanOrEqualTo(String value) {
            addCriterion("family_history <=", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryLike(String value) {
            addCriterion("family_history like", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryNotLike(String value) {
            addCriterion("family_history not like", value, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryIn(List<String> values) {
            addCriterion("family_history in", values, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryNotIn(List<String> values) {
            addCriterion("family_history not in", values, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryBetween(String value1, String value2) {
            addCriterion("family_history between", value1, value2, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andFamilyHistoryNotBetween(String value1, String value2) {
            addCriterion("family_history not between", value1, value2, "familyHistory");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationIsNull() {
            addCriterion("physical_examination is null");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationIsNotNull() {
            addCriterion("physical_examination is not null");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationEqualTo(String value) {
            addCriterion("physical_examination =", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationNotEqualTo(String value) {
            addCriterion("physical_examination <>", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationGreaterThan(String value) {
            addCriterion("physical_examination >", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationGreaterThanOrEqualTo(String value) {
            addCriterion("physical_examination >=", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationLessThan(String value) {
            addCriterion("physical_examination <", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationLessThanOrEqualTo(String value) {
            addCriterion("physical_examination <=", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationLike(String value) {
            addCriterion("physical_examination like", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationNotLike(String value) {
            addCriterion("physical_examination not like", value, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationIn(List<String> values) {
            addCriterion("physical_examination in", values, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationNotIn(List<String> values) {
            addCriterion("physical_examination not in", values, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationBetween(String value1, String value2) {
            addCriterion("physical_examination between", value1, value2, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andPhysicalExaminationNotBetween(String value1, String value2) {
            addCriterion("physical_examination not between", value1, value2, "physicalExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationIsNull() {
            addCriterion("therapeutic_examination is null");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationIsNotNull() {
            addCriterion("therapeutic_examination is not null");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationEqualTo(String value) {
            addCriterion("therapeutic_examination =", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationNotEqualTo(String value) {
            addCriterion("therapeutic_examination <>", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationGreaterThan(String value) {
            addCriterion("therapeutic_examination >", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationGreaterThanOrEqualTo(String value) {
            addCriterion("therapeutic_examination >=", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationLessThan(String value) {
            addCriterion("therapeutic_examination <", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationLessThanOrEqualTo(String value) {
            addCriterion("therapeutic_examination <=", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationLike(String value) {
            addCriterion("therapeutic_examination like", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationNotLike(String value) {
            addCriterion("therapeutic_examination not like", value, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationIn(List<String> values) {
            addCriterion("therapeutic_examination in", values, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationNotIn(List<String> values) {
            addCriterion("therapeutic_examination not in", values, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationBetween(String value1, String value2) {
            addCriterion("therapeutic_examination between", value1, value2, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andTherapeuticExaminationNotBetween(String value1, String value2) {
            addCriterion("therapeutic_examination not between", value1, value2, "therapeuticExamination");
            return (Criteria) this;
        }

        public Criteria andDiagnosisIsNull() {
            addCriterion("diagnosis is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisIsNotNull() {
            addCriterion("diagnosis is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosisEqualTo(String value) {
            addCriterion("diagnosis =", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNotEqualTo(String value) {
            addCriterion("diagnosis <>", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisGreaterThan(String value) {
            addCriterion("diagnosis >", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisGreaterThanOrEqualTo(String value) {
            addCriterion("diagnosis >=", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisLessThan(String value) {
            addCriterion("diagnosis <", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisLessThanOrEqualTo(String value) {
            addCriterion("diagnosis <=", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisLike(String value) {
            addCriterion("diagnosis like", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNotLike(String value) {
            addCriterion("diagnosis not like", value, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisIn(List<String> values) {
            addCriterion("diagnosis in", values, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNotIn(List<String> values) {
            addCriterion("diagnosis not in", values, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisBetween(String value1, String value2) {
            addCriterion("diagnosis between", value1, value2, "diagnosis");
            return (Criteria) this;
        }

        public Criteria andDiagnosisNotBetween(String value1, String value2) {
            addCriterion("diagnosis not between", value1, value2, "diagnosis");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}