package com.zuo.smartbackground.model;

public class Section {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.section_id
     *
     * @mbggenerated
     */
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.section_name
     *
     * @mbggenerated
     */
    private String sectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.section_introduction
     *
     * @mbggenerated
     */
    private String sectionIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.section_id
     *
     * @return the value of section.section_id
     *
     * @mbggenerated
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.section_id
     *
     * @param sectionId the value for section.section_id
     *
     * @mbggenerated
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.section_name
     *
     * @return the value of section.section_name
     *
     * @mbggenerated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.section_name
     *
     * @param sectionName the value for section.section_name
     *
     * @mbggenerated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.section_introduction
     *
     * @return the value of section.section_introduction
     *
     * @mbggenerated
     */
    public String getSectionIntroduction() {
        return sectionIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.section_introduction
     *
     * @param sectionIntroduction the value for section.section_introduction
     *
     * @mbggenerated
     */
    public void setSectionIntroduction(String sectionIntroduction) {
        this.sectionIntroduction = sectionIntroduction == null ? null : sectionIntroduction.trim();
    }
}