package com.zuo.smartbackground.dao;

import com.zuo.smartbackground.model.PatientRecord;
import com.zuo.smartbackground.model.PatientRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int countByExample(PatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int deleteByExample(PatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long patientRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int insert(PatientRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int insertSelective(PatientRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    List<PatientRecord> selectByExample(PatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    PatientRecord selectByPrimaryKey(Long patientRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PatientRecord record, @Param("example") PatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PatientRecord record, @Param("example") PatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PatientRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PatientRecord record);
}